### PR TITLE
Ignore packages containing "importjs": { "isRoot": false }

### PR DESCRIPTION
**Pull request by philolo1**
Based on https://github.com/Galooshi/import-js/pull/462 this enables to specify a property 
```
"importjs": { "isRoot": false }
```
to help find importjs the proper `package.json` file. 
@trotzig I adjusted the tests and the comments from the other pull request. Let me know if there is anything else I need to change.

### CODE REVIEW

**Comment by philolo1** [comment]
@trotzig i forked from the master branch, is it broken currently?

**Comment by trotzig** [comment]
Sorry for the late response here. Yes, it was most likely broken. Can you rebase/merge with master and try again?

**Comment by philolo1** [comment]
@trotzig i think we should be good now.

**Comment by trotzig** [comment]
This change is included in v3.2.0.

**Pull request merged**
